Get target directory from environment variable
The environment variable is named dynamically based on the name of the
program, so you could symlink the program under multiple names to target
multiple directories.

diff --git a/n b/n
--- a/n
+++ b/n
@@ -1,40 +1,41 @@
 #!/bin/sh
 
-# this variable contains the path to your notes
-notes=~/notes/
+name="$(basename $0)"
+eval env_dir=\$${name}DIR
+dir="${inter:-$HOME/notes/}"
 
 # this variable contains an optional suffix to remove from filenames
 suffix=".txt"
 
 # help text
-help="$(basename $0), for carefree note taking and reading
+help="$name, for carefree note taking and reading
 
-You can change your notes directory by editing "\$notes" in $(which $0)
+You can change your notes directory by editing "\$dir" in $(which $0)
 You can choose a file suffix to hide by editing "\$suffix" in $(which $0)
 
-Usage:	$(basename $0)				# print list of all notes
-	$(basename $0) <optional note> -w		# print path to notes or specific note
-	$(basename $0) <search string>		# if string is a note, open in editor
+Usage:	$name				# print list of all notes
+	$name <optional note> -w		# print path to notes or specific note
+	$name <search string>		# if string is a note, open in editor
 					# if not, search notes for string
-	$(basename $0) <note> -n			# open note in text editor
-	$(basename $0) -h OR -help OR --help		# print this help page
+	$name <note> -n			# open note in text editor
+	$name -h OR -help OR --help		# print this help page
 	Modes -n and -w can be placed before or after a note title.
 
 Report any bugs to <lfamular@gmail.com>
 "
 
 edit_note() {
-	${EDITOR:-vi} "$notes$1$suffix"
+	${EDITOR:-vi} "$dir$1$suffix"
 	return $?
 }
 
 ls_notes() {
-	ls -rt $notes | strip_suffix
+	ls -rt $dir | strip_suffix
 }
 
 search_notes() {
-	{ find -L $notes -iname "*$1*" | strip_prefix | strip_suffix ;
-	grep -iso -E ".{0,30}$1.{0,30}" $notes* \
+	{ find -L $dir -iname "*$1*" | strip_prefix | strip_suffix ;
+	grep -iso -E ".{0,30}$1.{0,30}" $dir* \
 	| strip_prefix \
 	| sed "s!$suffix:!\ :\ !" ; } \
 	| nl | sort -nr | cut -f2- \
@@ -43,7 +44,7 @@ search_notes() {
 
 strip_prefix() {
 	while read input; do
-		echo ${input#$notes}
+		echo ${input#$dir}
 	done
 }
 
@@ -55,10 +56,10 @@ strip_suffix() {
 
 which_notes() {
 	if [ -z "$1" ]; then
-		printf "$notes\n"
+		printf "$dir\n"
 	else
-		test -e "$notes$1$suffix" || { printf "File not found: " 1>&2; ret=1; }
-		printf "$notes$1$suffix\n"
+		test -e "$dir$1$suffix" || { printf "File not found: " 1>&2; ret=1; }
+		printf "$dir$1$suffix\n"
 	fi
 	return ${ret:-0}
 }
